# YOUR CODE HERE
apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connector
spec:
  selector:
    app: kafka-neo4j-connector
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
  labels:
    app: kafka-neo4j-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
        - name: kafka-neo4j-connector
          image: veedata/kafka-neo4j-connect:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
